
version: 2.1

jobs:
  build:
    docker:
      - image: cypress/included:3.2.0
    steps:
      - checkout
      - run: 'npm install'
      - run: 'npm run build'
      - run: 'npm run cypress'

workflows:
  my_workflow:
    jobs:
      - build